# Generated by Django 5.0.6 on 2024-07-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_set_default_company_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.RemoveField(
            model_name='selecteditem',
            name='company',
        ),
    ]
